# Generated by Django 4.0 on 2024-08-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100, verbose_name='Nome da Peça')),
                ('part_code', models.CharField(max_length=50, unique=True, verbose_name='Código da Peça')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('vehicle_compatibility', models.CharField(max_length=200, verbose_name='Compatibilidade com Veículos')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade em Estoque')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('supplier', models.CharField(max_length=100, verbose_name='Fornecedor')),
                ('purchase_date', models.DateField(verbose_name='Data de Aquisição')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['part_name'],
            },
        ),
    ]
